version: "3.8"

services:

  redis:
    container_name: redis
    image: 'redis:latest'
    restart: 'always'
    environment:
      - 'REDIS_HOST=redis'
      - 'REDIS_PORT=6379'
    ports:
      - '6379:6379'
    command:
      - 'redis-server'
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

  app:
    container_name: currency_bot
    build:
      context: .
    env_file: [../.env]
    command: ['python3', '-m', 'app']
    depends_on:
      - redis

networks:
  default:
    external:
      name: 'bot-redis-network'